spring.application.name=ney
# DATASOURCE
spring.datasource.url=jdbc:mysql://localhost:3306/dbney?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#se usa para limpiar y personalizar la vista de los errores generales
server.error.include-stacktrace=never
server.error.include-message=never


# para crear clave token con su respectivo tiempo de expiracion
security.jwt.secret=MI_CLAVE_SECRETA_SUPER_SEGURA_DE_MINIMO_32_CARACTERES_123456
security.jwt.expiration=86400000